modLoader="javafml"

loaderVersion="[39,)"

license="All rights reserved"

issueTrackerURL="https://github.com/Coliwogg/Gems-And-Crystals/issues"

[[mods]]

modId="gemsandcrystals"

version="1.18.1-1.3.5"

displayName="Gems and Crystals"

#updateJSONURL="http://myurl.me/"

displayURL="https://www.curseforge.com/minecraft/mc-mods/gems-and-crystals"

logoFile="logo.png"

credits="I would like to thank Tutorials by Kaupenjoe, TurtyWurty, TechnoVision, and Harry Talks for creating the tutorials that would enable me to make this mod."

authors="Coliwogg"

description='''Gems and Crystals mod for Minecraft 1.18.1.'''

[[dependencies.gemsandcrystals]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gemsandcrystals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"


