modLoader="javafml"

loaderVersion="[38,)"

license="All rights reserved"

issueTrackerURL="https://github.com/Coliwogg/Gems-And-Crystals/issues"

[[mods]]

modId="gemsandcrystals"

version="1.18-1.3.4"

displayName="Gems and Crystals"

#updateJSONURL="http://myurl.me/"

displayURL="https://www.curseforge.com/minecraft/mc-mods/gems-and-crystals"

logoFile="logo.png"

credits="Thanks for downloading this mod!"

authors="Coliwogg"

description='''Gems and Crystals mod for Minecraft 1.18.'''

[[dependencies.gemsandcrystals]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gemsandcrystals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"


