modLoader="javafml"

loaderVersion="[32,)"

license="All rights reserved"

issueTrackerURL="https://github.com/Coliwogg/Gems-And-Crystals/issues"

[[mods]]

modId="gemsandcrystals"

version="1.16.1-1.3.0"

displayName="Gems and Crystals"

#updateJSONURL="http://myurl.me/"

displayURL="https://www.curseforge.com/minecraft/mc-mods/gems-and-crystals"

logoFile="logo.png"

credits="Thanks for downloading this mod!"

authors="Coliwogg"

description='''Gems and Crystals mod for Minecraft 1.16.'''

[[dependencies.gemsandcrystals]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gemsandcrystals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
