modLoader="javafml"

loaderVersion="[31,)"

#issueTrackerURL="https://github.com/Coliwogg/Gems-And-Crystals-1.14.4/issues"

[[mods]]

modId="gemsandcrystals"

version="1.2.5c"

displayName="Gems and Crystals"

#updateJSONURL="http://myurl.me/"

displayURL="https://www.curseforge.com/minecraft/mc-mods/gems-and-crystals"

logoFile="logo.png"

credits="Thanks to YOU for downloading this mod"

authors="Coliwogg"

description='''
This mod adds multiple different kinds of gems and crystals to Minecraft version 1.15
It adds Rubies and Sapphires, along with craftable tools and armor. It also adds craftable Emerald tools and armor.
'''

[[dependencies.gemsandcrystals]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gemsandcrystals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
