name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java: [17]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build all modules
        run: ./gradlew clean build

      - name: Upload Fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabric-artifacts
          path: fabric/build/libs/

      - name: Upload NeoForge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neoforge-artifacts
          path: neoforge/build/libs/

      - name: Upload Common artifacts
        uses: actions/upload-artifact@v4
        with:
          name: common-artifacts
          path: common/build/libs/